import _ = require('lodash');

class Constant {

  public UPBIT_KRW_ALLALT_SPECIAL = 'KRW-ALLALT-SPECIAL';

  /* tslint:disable */
  public UPBIT_KRW_MARKET_SQUADS = [
    [ 'KRW-BTC', 'KRW-ETH',  'KRW-XRP', 'KRW-EOS', 'KRW-TRX', 'KRW-XLM', 'KRW-ADA', 'KRW-BCH', 'KRW-LTC' ],
    [ 'KRW-QTUM', 'KRW-OMG', 'KRW-CVC', 'KRW-POLY', 'KRW-STEEM', 'KRW-GRS', 'KRW-ZIL', 'KRW-IOTA', 'KRW-ARK', 'KRW-NEO' ]
  ];
  /* tslint:enable */

  public UPBIT_KRW_MARKET_BTC_ONLY = [ 'KRW-BTC' ];

  public UPBIT_ALL_KRW_MARKET_LIST = [
    'KRW-BTC',
    'KRW-ETH',
    'KRW-NEO',
    'KRW-MTL',
    'KRW-LTC',
    'KRW-STRAT',
    'KRW-XRP',
    'KRW-ETC',
    'KRW-OMG',
    'KRW-SNT',
    'KRW-WAVES',
    'KRW-XEM',
    'KRW-QTUM',
    'KRW-GNT',
    'KRW-LSK',
    'KRW-STEEM',
    'KRW-XLM',
    'KRW-ARDR',
    'KRW-KMD',
    'KRW-ARK',
    'KRW-STORJ',
    'KRW-GRS',
    'KRW-VTC',
    'KRW-REP',
    'KRW-EMC2',
    'KRW-ADA',
    'KRW-SBD',
    'KRW-POWR',
    'KRW-BTG',
    'KRW-ICX',
    'KRW-EOS',
    'KRW-STORM',
    'KRW-TRX',
    'KRW-MCO',
    'KRW-SC',
    'KRW-GTO',
    'KRW-IGNIS',
    'KRW-ONT',
    'KRW-DCR',
    'KRW-ZIL',
    'KRW-POLY',
    'KRW-ZRX',
    'KRW-SRN',
    'KRW-LOOM',
    'KRW-BCH',
    'KRW-ADT',
    'KRW-ADX',
    'KRW-BAT',
    'KRW-IOST',
    'KRW-DMT',
    'KRW-RFR',
    'KRW-CVC',
    'KRW-IQ',
    'KRW-IOTA',
    'KRW-OST',
    'KRW-MFT',
    'KRW-ONG',
    'KRW-GAS',
    'KRW-UPP',
    'KRW-ELF',
    'KRW-KNC',
    'KRW-BSV',
    'KRW-THETA',
    'KRW-EDR',
    'KRW-QKC',
    'KRW-CPT',
    'KRW-BTT',
    'KRW-MOC',
    'KRW-COSM',
    'KRW-ENJ',
    'KRW-TFUEL',
    'KRW-MANA',
    'KRW-ANKR',
    'KRW-NPXS',
    'KRW-TTC',
    'KRW-AERGO',
    'KRW-ATOM',
    'KRW-TT',
    'KRW-CRE',
    'KRW-SOLVE',
    'KRW-MBL',
    'KRW-TSHP',
    'KRW-WAXP',
    'KRW-HBAR',
    'KRW-MED'
  ];

  public UPBIT_ALL_BTC_MARKET_LIST = [
    'BTC-ETH',
    'BTC-LTC',
    'BTC-STRAT',
    'BTC-XRP',
    'BTC-ETC',
    'BTC-OMG',
    'BTC-CVC',
    'BTC-DGB',
    'BTC-PAY',
    'BTC-SC',
    'BTC-SNT',
    'BTC-XVG',
    'BTC-WAVES',
    'BTC-NMR',
    'BTC-GBYTE',
    'BTC-XEM',
    'BTC-LBC',
    'BTC-QTUM',
    'BTC-GNT',
    'BTC-NXT',
    'BTC-BAT',
    'BTC-XEL',
    'BTC-LSK',
    'BTC-RDD',
    'BTC-DCT',
    'BTC-STEEM',
    'BTC-GAME',
    'BTC-FCT',
    'BTC-PTOY',
    'BTC-DCR',
    'BTC-DOGE',
    'BTC-BNT',
    'BTC-XLM',
    'BTC-PART',
    'BTC-MCO',
    'BTC-UBQ',
    'BTC-ARDR',
    'BTC-KMD',
    'BTC-ARK',
    'BTC-ADX',
    'BTC-SYS',
    'BTC-ANT',
    'BTC-MUE',
    'BTC-XDN',
    'BTC-STORJ',
    'BTC-QRL',
    'BTC-NXS',
    'BTC-GRS',
    'BTC-VTC',
    'BTC-SIB',
    'BTC-REP',
    'BTC-VIA',
    'BTC-SWT',
    'BTC-MONA',
    'BTC-AMP',
    'BTC-HMQ',
    'BTC-RLC',
    'BTC-BLOCK',
    'BTC-MEME',
    'BTC-OK',
    'BTC-XZC',
    'BTC-ADT',
    'BTC-FTC',
    'BTC-ION',
    'BTC-GNO',
    'BTC-EMC2',
    'BTC-EXCL',
    'BTC-EXP',
    'BTC-VRC',
    'BTC-BURST',
    'BTC-SHIFT',
    'BTC-BLK',
    'BTC-ZEN',
    'BTC-RADS',
    'BTC-NAV',
    'BTC-ADA',
    'BTC-MANA',
    'BTC-SBD',
    'BTC-RCN',
    'BTC-VIB',
    'BTC-POWR',
    'BTC-ENG',
    'BTC-UKG',
    'BTC-DNT',
    'BTC-IGNIS',
    'BTC-SRN',
    'BTC-ZRX',
    'BTC-VEE',
    'BTC-BCPT',
    'BTC-TRX',
    'BTC-TUSD',
    'BTC-LRC',
    'BTC-RVR',
    'BTC-UP',
    'BTC-DMT',
    'BTC-POLY',
    'BTC-PRO',
    'BTC-BLT',
    'BTC-STORM',
    'BTC-AID',
    'BTC-NGC',
    'BTC-GTO',
    'BTC-OCN',
    'BTC-CMCT',
    'BTC-BCH',
    'BTC-BKX',
    'BTC-MFT',
    'BTC-LOOM',
    'BTC-RFR',
    'BTC-RVN',
    'BTC-BFT',
    'BTC-GO',
    'BTC-UPP',
    'BTC-ENJ',
    'BTC-MET',
    'BTC-HYDRO',
    'BTC-CRW',
    'BTC-DTA',
    'BTC-EDR',
    'BTC-BOXX',
    'BTC-IHT',
    'BTC-MTL',
    'BTC-PMA',
    'BTC-PAL',
    'BTC-PAX',
    'BTC-MOC',
    'BTC-NPXS',
    'BTC-ZIL',
    'BTC-OST',
    'BTC-MEDX',
    'BTC-SPC',
    'BTC-BSV',
    'BTC-IOST',
    'BTC-XNK',
    'BTC-NCASH',
    'BTC-JNT',
    'BTC-LBA',
    'BTC-DENT',
    'BTC-DRGN',
    'BTC-BTM',
    'BTC-ELF',
    'BTC-BTT',
    'BTC-VITE',
    'BTC-IOTX',
    'BTC-BTU',
    'BTC-SOLVE',
    'BTC-NKN',
    'BTC-QNT',
    'BTC-CTXC',
    'BTC-SPND',
    'BTC-META',
    'BTC-SERV',
    'BTC-ANKR',
    'BTC-CRO',
    'BTC-BTS',
    'BTC-FSN',
    'BTC-TTC',
    'BTC-VBK',
    'BTC-ORBS',
    'BTC-AERGO',
    'BTC-PI',
    'BTC-VDX',
    'BTC-COSM',
    'BTC-ATOM',
    'BTC-STPT',
    'BTC-CPT',
    'BTC-LAMB',
    'BTC-EOS',
    'BTC-LUNA',
    'BTC-DAI',
    'BTC-MKR',
    'BTC-BORA',
    'BTC-TSHP',
    'BTC-WAXP'
  ];

  public UPBIT_ALL_ETH_MARKET_LIST = [
    'ETH-LTC',
    'ETH-STRAT',
    'ETH-XRP',
    'ETH-ETC',
    'ETH-OMG',
    'ETH-CVC',
    'ETH-DGB',
    'ETH-PAY',
    'ETH-SC',
    'ETH-SNT',
    'ETH-WAVES',
    'ETH-XEM',
    'ETH-QTUM',
    'ETH-GNT',
    'ETH-BAT',
    'ETH-BNT',
    'ETH-XLM',
    'ETH-MCO',
    'ETH-ADX',
    'ETH-ANT',
    'ETH-REP',
    'ETH-GNO',
    'ETH-MANA',
    'ETH-VIB',
    'ETH-POWR',
    'ETH-SRN',
    'ETH-ZRX',
    'ETH-TRX',
    'ETH-TUSD',
    'ETH-ADA',
    'ETH-ENG',
    'ETH-UKG',
    'ETH-DMT',
    'ETH-STORM',
    'ETH-OCN',
    'ETH-BCH',
    'ETH-WAXP'
  ];

  public UPBIT_ALL_USDT_MARKET_LIST = [
    'USDT-BTC',
    'USDT-ETH',
    'USDT-LTC',
    'USDT-XRP',
    'USDT-ETC',
    'USDT-OMG',
    'USDT-XVG',
    'USDT-ADA',
    'USDT-TUSD',
    'USDT-SC',
    'USDT-TRX',
    'USDT-DCR',
    'USDT-BCH',
    'USDT-DGB',
    'USDT-DOGE',
    'USDT-ZRX',
    'USDT-RVN',
    'USDT-BAT'
  ];

  public UPBIT_ALL_MARKET_LIST = this.UPBIT_ALL_BTC_MARKET_LIST
                                .concat(this.UPBIT_ALL_ETH_MARKET_LIST)
                                .concat(this.UPBIT_ALL_KRW_MARKET_LIST)
                                .concat(this.UPBIT_ALL_USDT_MARKET_LIST);

  public updateFromMarketAll(v) {
    _.remove(this.UPBIT_ALL_KRW_MARKET_LIST);
    _.remove(this.UPBIT_ALL_BTC_MARKET_LIST);
    _.remove(this.UPBIT_ALL_USDT_MARKET_LIST);
    _.remove(this.UPBIT_ALL_MARKET_LIST);

    v.forEach(element => {
      const market: string = element.market;
      switch (market.substr(0, 3)) {
        case 'KRW': this.UPBIT_ALL_KRW_MARKET_LIST.push(market); break;
        case 'BTC': this.UPBIT_ALL_BTC_MARKET_LIST.push(market); break;
        case 'USTD': this.UPBIT_ALL_USDT_MARKET_LIST.push(market); break;
      }
    });

    console.log(JSON.stringify(this.UPBIT_ALL_KRW_MARKET_LIST));
    console.log(JSON.stringify(this.UPBIT_ALL_BTC_MARKET_LIST));
    console.log(JSON.stringify(this.UPBIT_ALL_USDT_MARKET_LIST));

    this.UPBIT_ALL_MARKET_LIST = this.UPBIT_ALL_MARKET_LIST
     .concat(this.UPBIT_ALL_BTC_MARKET_LIST)
     .concat(this.UPBIT_ALL_KRW_MARKET_LIST)
     .concat(this.UPBIT_ALL_USDT_MARKET_LIST);

  }
}

export const constant = new Constant;
