{
 "title": "Upbit BTC Accumulated Volume Increase for All coins",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ETH, XRP, ETC, DOGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ETH\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-XRP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ETC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-DOGE\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "LTC, BSV, BCH, ADA, EOS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-LTC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BSV\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BCH\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ADA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-EOS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "BTG, NEO, STRK 50000~70000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-NEO\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BTG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STRK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "REP, BCHA, LINK, DOT, WAVES / 20000~30000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-REP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BCHA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-LINK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-DOT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-WAVES\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "FLOW, ATOM, QTUM, GAS, TON / 10000~20000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-FLOW\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ATOM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-QTUM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-GAS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-TON\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "THETA, CBK, SBD, OMG, SRM, AQT, LSK / 5000~9000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-THETA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-CBK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SBD\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-OMG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SRM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-AQT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-LSK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "AXS, XTZ, KAVA, DAWN, STRAX, MTL / 3000 ~5000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-AXS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-XTZ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-KAVA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-DAWN\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STRAX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MTL\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SXP, KNC, MLK, KMD, PUNDIX, STORJ / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-KNC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MLK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SXP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-KMD\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-PUNDIX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STORJ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ARK, DMT, ICX, IOTA, ENJ, ONT, PCI / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ARK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-DMT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ICX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-IOTA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ENJ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ONT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-PCI\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ZRX, STX, GRS, ONG, ADX, / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-GRS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ZRX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-GRS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ONG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ADX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "MANA, BAT, STEEM, HIVE, HUNT, XLM, PLA / 400~1000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MANA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BAT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STEEM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-HIVE\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-HUNT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-XLM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-PLA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SAND, CVC, MARO, EMC2, GLM, ELF / 200~500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SAND\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-CVC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MARO\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-EMC2\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-GLM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ELF\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "TFUEL, POWR, POLY, HBAR, CHZ, ABDR / 200 ~ 500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-TFUEL\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-POWR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-POLY\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-HBAR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-CHZ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ABDR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SOLVE, AERGO, XEM, BORA, FCT2, WAXP, DKA, MOC / 100~300",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SOLVE\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-AERGO\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-XEM\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BORA\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-FCT2\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-WAXP\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-DKA\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MOC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ZIL, CRO, ANKR, LBC, UPP, META, IGNIS, VET / 100~300",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ZIL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-CRO\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ANKR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-LBC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-UPP\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-META\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-IGNIS\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-VET\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "HUM, SNT, LOOM, ORBS, SSX, MED, PXL, TRX / 50~150",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-HUM\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SNT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-LOOM\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-ORBS\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SSX\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MED\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-PXL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-TRX\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "JST, LAMB, STPT, QTCON, EDR, IOST, STMX, QKC, / ~100",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-JST\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-LAMB\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STPT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-QTCON\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-EDR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-IOST\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-STMX\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-QKC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SC, MVL, OBSR, TSHP, RFR, IQ, AHT, TT, MFT, MBL / ~100",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-SC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MVL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-OBSR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-TSHP\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-RFR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-IQ\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-AHT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-TT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MFT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-MBL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-CRE\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"BTC-BTT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  }
 ]
}