{
 "title": "Upbit_KRW_Accumulated_ASK_BID_volume",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "BTC vs ALT Accumulated Price",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit { market=\"KRW-BTC\", info=\"candle_acc_trade_price\" }",
     "legendFormat": "{{market}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { type=\"KRW-ALLALT-SPECIAL\", info=\"candle_acc_trade_price\" }",
     "legendFormat": "{{type}}-{{info}}"
    }
   ]
  },
  {
   "title": "KRW-BTC ASK/BID Acc Volume",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exchg_upbit { market=\"KRW-BTC\", info=\"acc_ask_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { market=\"KRW-BTC\", info=\"acc_bid_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    }
   ]
  },
  {
   "title": "All Alt Coins ASK/BID Acc Volume",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exchg_upbit { type=\"KRW-ALLALT-SPECIAL\", info=\"acc_ask_volume\" }",
     "legendFormat": "{{type}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { type=\"KRW-ALLALT-SPECIAL\", info=\"acc_bid_volume\" }",
     "legendFormat": "{{type}}-{{info}}"
    }
   ]
  },
  {
   "title": "KRW-BTC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit { market= \"KRW-BTC\", info=\"acc_ask_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { market= \"KRW-BTC\", info=\"acc_bid_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    }
   ]
  },
  {
   "title": "AltCoins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit { type= \"KRW-ALLALT-SPECIAL\", info=\"acc_ask_volume\" }",
     "legendFormat": "{{type}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { type= \"KRW-ALLALT-SPECIAL\", info=\"acc_bid_volume\" }",
     "legendFormat": "{{type}}-{{info}}"
    }
   ]
  },
  {
   "title": "KRW-ETH",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit { market= \"KRW-ETH\", info=\"acc_ask_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { market= \"KRW-ETH\", info=\"acc_bid_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    }
   ]
  },
  {
   "title": "KRW-XRP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit { market= \"KRW-XRP\", info=\"acc_ask_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    },
    {
     "expr": "exchg_upbit { market= \"KRW-XRP\", info=\"acc_bid_volume\" }",
     "legendFormat": "{{market}}-{{info}}"
    }
   ]
  }
 ]
}