{
 "title": "Upbit_BTC_market_Price_ALL_COINS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "ETH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-ETH\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "BCH",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-BCH\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "LTC, BSV,",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-LTC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-BSV\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ETC, BTG, NEO, STRK 50000~70000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-ETC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-NEO\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-BTG\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STRK\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "REP, BCHA, LINK, DOT, WAVES / 20000~30000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-REP\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-BCHA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-LINK\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-DOT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-WAVES\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "FLOW, ATOM, QTUM, GAS, TON / 10000~20000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-FLOW\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ATOM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-QTUM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-GAS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-TON\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "THETA, CBK, SBD, OMG, EOS, SRM, AQT, LSK / 5000~9000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-THETA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-CBK\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-SBD\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-OMG\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-EOS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-SRM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-AQT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-LSK\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "AXS, XTZ, KAVA, DAWN, STRAX, MTL / 3000 ~5000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-AXS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-XTZ\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-KAVA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-DAWN\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STRAX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MTL\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SXP, KNC, ADA, MLK, KMD, PUNDIX, STORJ / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-KNC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ADA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MLK\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-SXP\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-KMD\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-PUNDIX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STORJ\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ARK, DMT, ICX, IOTA, ENJ, ONT, PCI / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-ARK\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-DMT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ICX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-IOTA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ENJ\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ONT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-PCI\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "XRP, ZRX, STX, GRS, ONG, ADX, / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-XRP\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-GRS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ZRX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-GRS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ONG\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ADX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "MANA, BAT, STEEM, HIVE, HUNT, XLM, PLA / 400~1000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-MANA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-BAT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STEEM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-HIVE\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-HUNT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-XLM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-PLA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "DOGE, SAND, CVC, MARO, EMC2, GLM, ELF / 200~500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-DOGE\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-SAND\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-CVC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MARO\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-EMC2\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-GLM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ELF\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "TFUEL, POWR, POLY, HBAR, CHZ, ABDR / 200 ~ 500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-TFUEL\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-POWR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-POLY\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-HBAR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-CHZ\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ABDR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SOLVE, AERGO, XEM, BORA, FCT2, WAXP, DKA, MOC / 100~300",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-SOLVE\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-AERGO\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-XEM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-BORA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-FCT2\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-WAXP\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-DKA\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MOC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ZIL, CRO, ANKR, LBC, UPP, META, IGNIS, VET / 100~300",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-ZIL\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-CRO\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ANKR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-LBC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-UPP\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-META\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-IGNIS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-VET\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "HUM, SNT, LOOM, ORBS, SSX, MED, PXL, TRX / 50~150",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-HUM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-SNT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-LOOM\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-ORBS\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-SSX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MED\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-PXL\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-TRX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "JST, LAMB, STPT, QTCON, EDR, IOST, STMX, QKC, / ~100",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-JST\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-LAMB\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STPT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-QTCON\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-EDR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-IOST\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-STMX\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-QKC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SC, MVL, OBSR, TSHP, RFR, IQ, AHT, TT, MFT, MBL / ~100",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "exchg_upbit {market=\"BTC-SC\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MVL\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-OBSR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-TSHP\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-RFR\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-IQ\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-AHT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-TT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MFT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-MBL\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-CRE\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "exchg_upbit {market=\"BTC-BTT\", info=\"trade_price\"}",
     "legendFormat": "{{market}}"
    }
   ]
  }
 ]
}