{
 "title": "Upbit_Accumulated_Price_Increase_Interesting_COINS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "메이저 거래량 BTC/ETH/XRP/BCH/ADA/DOGE/EOS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-BTC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ETH\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-XRP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-BCH\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ADA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-DOGE\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ADA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-EOS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "시총 상위권 거래량 XML/DOT/LTC/LINK/NEO/QTUM/ETC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-XLM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-DOT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-LTC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-LINK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-NEO\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-QTUM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ETC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "잡트 거래량 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-XTZ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-OMG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ZIL\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-LAMB\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-IOST\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-REP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ZIL\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-KAVA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-BCHA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ZRX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "잡트 거래량 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-UPP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-EDR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-MOC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-CRE\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-LBC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-SRM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-DAWN\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "잡트 거래량 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-DMT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-HUNT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ONG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-MANA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-ONT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-STORJ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase( exchg_upbit { job=\"upbit-exporter\", market=\"KRW-GAS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  }
 ]
}