{
 "title": "Upbit_KRW_Accumulated_Price_Increase_ALL_COINS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "BTC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BTC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ETH, XRP, ETC, DOGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ETH\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-XRP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ETC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-DOGE\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "LTC, BSV, BCH, ADA, EOS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-LTC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BSV\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BCH\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ADA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-EOS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "BTG, NEO, STRK 50000~70000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-NEO\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BTG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STRK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "REP, BCHA, LINK, DOT, WAVES / 20000~30000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-REP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BCHA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-LINK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-DOT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-WAVES\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "FLOW, ATOM, QTUM, GAS, TON / 10000~20000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-FLOW\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ATOM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-QTUM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-GAS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-TON\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "THETA, CBK, SBD, OMG, SRM, AQT, LSK / 5000~9000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-THETA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-CBK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SBD\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-OMG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SRM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-AQT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-LSK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "AXS, XTZ, KAVA, DAWN, STRAX, MTL / 3000 ~5000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-AXS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-XTZ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-KAVA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-DAWN\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STRAX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MTL\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SXP, KNC, MLK, KMD, PUNDIX, STORJ / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-KNC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MLK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SXP\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-KMD\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-PUNDIX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STORJ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ARK, DMT, ICX, IOTA, ENJ, ONT, PCI / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ARK\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-DMT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ICX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-IOTA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ENJ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ONT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-PCI\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ZRX, STX, GRS, ONG, ADX, / 1000~3000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-GRS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ZRX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-GRS\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ONG\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ADX\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "MANA, BAT, STEEM, HIVE, HUNT, XLM, PLA / 400~1000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MANA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BAT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STEEM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-HIVE\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-HUNT\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-XLM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-PLA\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SAND, CVC, MARO, EMC2, GLM, ELF / 200~500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SAND\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-CVC\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MARO\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-EMC2\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-GLM\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ELF\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "TFUEL, POWR, POLY, HBAR, CHZ, ABDR / 200 ~ 500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-TFUEL\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-POWR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-POLY\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-HBAR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-CHZ\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ABDR\", info=\"candle_acc_trade_price\"} [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SOLVE, AERGO, XEM, BORA, FCT2, WAXP, DKA, MOC / 100~300",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SOLVE\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-AERGO\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-XEM\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BORA\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-FCT2\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-WAXP\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-DKA\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MOC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "ZIL, CRO, ANKR, LBC, UPP, META, IGNIS, VET / 100~300",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ZIL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-CRO\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ANKR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-LBC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-UPP\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-META\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-IGNIS\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-VET\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "HUM, SNT, LOOM, ORBS, SSX, MED, PXL, TRX / 50~150",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-HUM\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SNT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-LOOM\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-ORBS\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SSX\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MED\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-PXL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-TRX\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "JST, LAMB, STPT, QTCON, EDR, IOST, STMX, QKC, / ~100",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-JST\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-LAMB\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STPT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-QTCON\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-EDR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-IOST\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-STMX\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-QKC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  },
  {
   "title": "SC, MVL, OBSR, TSHP, RFR, IQ, AHT, TT, MFT, MBL / ~100",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-SC\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MVL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-OBSR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-TSHP\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-RFR\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-IQ\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-AHT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-TT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MFT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-MBL\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-CRE\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    },
    {
     "expr": "increase(exchg_upbit  {market=\"KRW-BTT\", info=\"candle_acc_trade_price\"}  [5m])",
     "legendFormat": "{{market}}"
    }
   ]
  }
 ]
}